In [ ]:
import pandas as pd 
from scripts.parser_cotahist import ler_cotahist

df = ler_cotahist("dados_brutos/COTAHIST_A2024.TXT", nrows=100)
df.head()

ModuleNotFoundError: No module named 'scripts.parser_cotahist'

In [4]:
caminho = "dados_brutos/COTAHIST_A2024.TXT"

df_raw = pd.read_fwf(caminho)

df_raw.head()

,00COTAHIST.2024BOVESPA,20241231,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,012024010202AALR3,010ALLIAR ON,NaN,NM,R$,0000000001020000000000103600000000008500000000...
1,012024010202ABCB4,010ABC BRASIL PN,EJS,N2,R$,0000000002398000000000239800000000022790000000...
2,012024010202ABEV3,010AMBEV S/A ON,EJ,NaN,R$,0000000001372000000000137300000000013590000000...
3,012024010202BBDC3,010BRADESCO ON,EJ,N1,R$,0000000001526000000000152600000000014980000000...
4,012024010202ALPA3,010ALPARGATAS ON,NaN,N1,R$,0000000001011000000000103000000000009990000000...

In [ ]:
colspecs = [
    (0, 2),
    (2, 10),
    (12, 24),
    (27, 39),
    (56, 69),
    (108, 121),
    (170, 188)
]

colunas = [
    "tipo_registro",
    "data",
    "codigo_acao",
    "nome_empresa",
    "preco_abertura",
    "preco_fechamento",
    "volume"
]


df = pd.read_fwf(
    caminho,
     colspecs=colspecs,
      names=colunas,
       dtype={"tipo_registro": str},
       nrows=20
       )

df.head()

,tipo_registro,data,codigo_acao,nome_empresa,preco_abertura,preco_fechamento,volume
0,00,COTAHIST,024BOVESPA 2,1231,NaN,NaN,NaN
1,01,20240102,AALR3,ALLIAR,1020.0,850.0,4.014875e+08
2,01,20240102,ABCB4,ABC BRASIL,2398.0,2288.0,4.494731e+09
3,01,20240102,ABEV3,AMBEV S/A,1372.0,1371.0,1.598391e+10
4,01,20240102,BBDC3,BRADESCO,1526.0,1511.0,6.857685e+09

In [11]:
df = df[df["tipo_registro"] == "1"]

df.head(10)

Empty DataFrame
Columns: [tipo_registro, data, codigo_acao, nome_empresa, preco_abertura, preco_fechamento, volume]
Index: []